### ISSUE TITLE
[nailgun] Unable to create entities without search mixin

### ISSUE THREAD

**Issue by chbrown13** [SatelliteQE/satellite-populate#74]
* satellite-populate version:
* Python version: 2.7.13
* Operating System: Fedora 25

### Description

Several nailgun entities with the EntityCreateMixin, which provides the ability to create the entity, fail during the create action if they don't have the EntitySearchMixin because a search is executed during create.

### What I Did

```
Traceback (most recent call last):
  File "/opt/virtual_env/satellite-populate/bin/satellite-populate", line 11, in <module>
    load_entry_point('satellite-populate', 'console_scripts', 'satellite-populate')()
  File "/opt/virtual_env/satellite-populate/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/virtual_env/satellite-populate/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/virtual_env/satellite-populate/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/virtual_env/satellite-populate/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/chris/Documents/satellite-populate/satellite_populate/commands.py", line 161, in main
    hostname, username, password, report, enable_output)
  File "/home/chris/Documents/satellite-populate/satellite_populate/commands.py", line 47, in execute_populate
    enable_output=enable_output
  File "/home/chris/Documents/satellite-populate/satellite_populate/main.py", line 62, in populate
    populator.execute()
  File "/home/chris/Documents/satellite-populate/satellite_populate/base.py", line 186, in execute
    entity_data, action_data, search, action
  File "/home/chris/Documents/satellite-populate/satellite_populate/api.py", line 39, in populate
    rendered_action_data, action_data, search, model, silent_errors
  File "/home/chris/Documents/satellite-populate/satellite_populate/api.py", line 58, in action_create
    model, search, unique=True, silent_errors=silent_errors
  File "/home/chris/Documents/satellite-populate/satellite_populate/base.py", line 602, in get_search_result
    raise TypeError("{0} not searchable".format(model.__name__))
TypeError: ComputeProfile not searchable
```

**Comment by chbrown13** [comment]
Running list of entities facing this problem:

AuthSourceLDAP
ComputeAttribute
ComputeProfile
DiscoveredHost

**Comment by chbrown13** [comment]
This also causes an error with update and delete actions. @rochacbruno Should it be possible for nailgun entities to have update and delete entity mixins without being searchable?
